name: Add to DevOps Project

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add_to_project:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        flag:
          - flag

    steps:
      - name: Add issue/PR to GitHub Project
        if: github.event.label.name == '${{ matrix.flag }}'
        uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/lando/projects/10
          github-token: ${{ secrets.SHADOW_COUNCIL_ESCALATOR }}
          labeled: ${{ matrix.flag }}
